from langchain_openai import ChatOpenAI
from deepeval.test_case import LLMTestCase
from deepeval.metrics import AnswerRelevancyMetric, ContextualPrecisionMetric, FaithfulnessMetric, ContextualRelevancyMetric, ContextualRecallMetric
from deepeval import evaluate
from dotenv import load_dotenv
import os
import sys

# Load environment variables first
load_dotenv(dotenv_path='../.env')

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from rag import RAG

answer_relevancy = AnswerRelevancyMetric(threshold=0.8, model="gpt-4.1-mini")
contextual_precision = ContextualPrecisionMetric(threshold=0.8, model="gpt-4.1-mini")
contextual_relevancy = ContextualRelevancyMetric(threshold=0.6, model="gpt-4.1-mini")
contextual_recall = ContextualRecallMetric(threshold=0.8, model="gpt-4.1-mini")
faithfulness = FaithfulnessMetric(threshold=0.8, model="gpt-4.1-mini")

llm = ChatOpenAI(
    base_url="https://api.openai.com/v1",
    api_key=os.getenv('OPENAI_API_KEY'),
    model="gpt-4.1-mini",
    temperature=0.1,
    max_tokens=1000,
)

facility_guide_test_cases = [
    LLMTestCase(
        input='How to handle system alerts triggered by monitoring tools?',
        expected_output=(
            'When an incident ticket is generated by a system alert, the support team must check the '
            'system health status (via API) and the time since the last system activity. A successful health '
            'status means the application and database are healthy. If the time since last activity is under '
            '10 minutes, the system is considered healthy and the ticket should be closed. If the time is '
            '10 minutes or more, the system may be unhealthy, and the ticket should remain open and be '
            'assigned to the Application Administrator for investigation.'
        )
    ),
    LLMTestCase(
        input='After submitting a booking request, the screen is blank.',
        expected_output=(
            'If a user reports an error after attempting a facility booking and is unsure if it was successful, '
            'the support team must first use the health check API to verify the system\'s operational '
            'status. If the system is healthy (both the application and database are functioning), the user '
            'should be instructed to re-log in and confirm their booking history, allowing the incident ticket '
            'to be closed. Conversely, if the health check API detects a system error, the ticket must stay '
            'open and be escalated to the Application Administrator for further investigation.'
        )
    ),
]

infosecurity_guide_test_cases = [
    LLMTestCase(
        input='What is the password policy for the organization?',
        expected_output=(
            '1.1 Password Length\n'
            '● User account passwords must be at least 8 characters in length.\n'
            '● Privileged or administrative account passwords must be at least 12 characters.\n'
            '1.2 Password Complexity\n'
            'Passwords must include at least three (3) of the following four (4) character types:\n'
            '● Uppercase letters (A–Z)\n'
            '● Lowercase letters (a–z)\n'
            '● Numbers (0–9)\n'
            '● Special characters (e.g. ! @ # $ % ^ & *)\n'
        )
    )
]

def test_rag_facility_guide():

    rag = RAG(
        model=llm,
        api_key=os.getenv("PINECONE_API_KEY"),
        host=os.getenv("PINECONE_HOST_FACILITY_GUIDE"),
        index_name=os.getenv("PINECONE_INDEX_NAME_FACILITY_GUIDE")
    )

    for test_case in facility_guide_test_cases:

        actual_output, retrieved_contexts = rag.query(test_case.input)

        test_case.actual_output = actual_output
        test_case.retrieval_context = retrieved_contexts

    evaluate(facility_guide_test_cases, metrics=[answer_relevancy, contextual_precision, faithfulness, contextual_relevancy, contextual_recall])

def test_rag_infosecurity_guide():

    rag = RAG(
        model=llm,
        api_key=os.getenv("PINECONE_API_KEY"),
        host=os.getenv("PINECONE_HOST_INFOSEC_POLICY"),
        index_name=os.getenv("PINECONE_INDEX_NAME_INFOSEC_POLICY")
    )

    for test_case in infosecurity_guide_test_cases:

        actual_output, retrieved_contexts = rag.query(test_case.input, top_k=2)

        test_case.actual_output = actual_output
        test_case.retrieval_context = retrieved_contexts

    evaluate(infosecurity_guide_test_cases, metrics=[answer_relevancy, contextual_precision, faithfulness, contextual_relevancy, contextual_recall])

if __name__ == "__main__":
    test_rag_facility_guide()
    # test_rag_infosecurity_guide()
    sys.exit(0)



